FROM node:22-alpine

RUN corepack enable && corepack prepare pnpm@latest --activate

ENV PNPM_CONFIG_TRUST_LOCKFILE=true

WORKDIR /app

COPY package.json pnpm-workspace.yaml pnpm-lock.yaml ./
COPY apps/api/package.json ./apps/api/
COPY packages/types/package.json ./packages/types/

RUN pnpm install --frozen-lockfile

COPY tsconfig.base.json ./
COPY packages/types ./packages/types
COPY apps/api ./apps/api

WORKDIR /app/apps/api

EXPOSE 3001
CMD ["sh", "-c", "/app/node_modules/.bin/prisma generate && pnpm dev"]
